### ISSUE TITLE
Stop working

### ISSUE THREAD

**Issue by emersonbottero** [ebidel/geo-location#10]
It was workig a few days ago but now it only returns 
2: Network location provider at 'https://www.googleapis.com/' : Returned error code 403.

Do I need an API_Key and set it somewere or it is realy bugged now?

**Comment by emersonbottero** [comment]
It came back, but i still receive htis message in console!

getCurrentPosition() and watchPosition() are deprecated on insecure origins, and support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details

**Comment by ebidel** [comment]
What browser and version are you using?

**Comment by ebidel** [comment]
The demo still works for me on https://ebidel.github.io/geo-location/components/geo-location/

**Comment by emersonbottero** [comment]
It oscillates, now it's working fine.
