### ISSUE TITLE
Watch position when multiple geo-location elements

### ISSUE THREAD

**Issue by rbellens** [ebidel/geo-location#22]
When you add multiple geo-location elements with watch-pos in a single document, only one will effectively watch the position. The watch for the other elements is cleared. Is this on purpose?

Possible fix in this fork: https://github.com/appsup-polymer/geo-location

**Comment by ebidel** [comment]
Not on purpose!

The fix you have is correct. That is make https://github.com/ebidel/geo-location/blob/master/geo-location.html#L37 a member of the element so watch instance has its own state.

Feel free to submit a PR. I'm happy to take that change :)

**Comment by rbellens** [comment]
ok, great. see PR https://github.com/ebidel/geo-location/pull/23

**Comment by FluorescentHallucinogen** [comment]
#23 is merged. I think this issue can be closed.
