### ISSUE TITLE
Upgrade to Polymer 2.x

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [ebidel/geo-location#24]
@ebidel Please update this web component to Polymer 2.x support.

**Comment by ebidel** [comment]
I'm not planning to update this component with newer versions of Polymer. Pull requests welcome though :)

**Comment by motss** [comment]
OK. Totes interested in working the PR. 😸

**Comment by sheideman** [comment]
I just upgraded the element to 2.0 and it preliminarily is working, but I want to do some cross device/browser tests. I will do a PR in the next day or two.  👍

**Comment by ebidel** [comment]
Thanks!

**Comment by paales** [comment]
@sheideman Your updated version is not public?

**Comment by FluorescentHallucinogen** [comment]
@paales See #25.

**Comment by paales** [comment]
Ohhh! I can't wait!

**Comment by Oupsla** [comment]
Any news guys ?

**Comment by ebidel** [comment]
https://github.com/ebidel/geo-location/pull/25 was closed by the author. If anyone else wants to pick it back up and re-submit, I'm happy to take a look.

**Comment by FluorescentHallucinogen** [comment]
What an open source!.. I'll send a pull request as soon as I have some free time. :wink:

**Comment by FluorescentHallucinogen** [comment]
See #27. :wink:

**Comment by FluorescentHallucinogen** [comment]
Fixed by merging #27.
