### ISSUE TITLE
Repo description

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [ebidel/geo-location#28]
- [x] Add keywords from `bower.json` as repo topics (https://github.com/blog/2309-introducing-topics).
- [x] Change link https://ebidel.github.io/geo-location/ to https://webcomponents.org/element/ebidel/geo-location.

It makes sense to remove the https://ebidel.github.io/geo-location/ demo ([gh-pages](https://github.com/ebidel/geo-location/tree/gh-pages) branch) completely, because:

1. it's outdated
2. the https://webcomponents.org catalog obsoletes the creation of GitHub pages for Polymer documentation and demos (see https://medium.com/collaborne-engineering/polymer-simplify-travis-builds-with-webcomponents-org-f44c3a879f3c)

**Comment by ebidel** [comment]
done

**Comment by FluorescentHallucinogen** [comment]
@ebidel 
1. Why you have added **not all** keywords from `bower.json`?
2. Could you please update the content of [gh-pages](https://github.com/ebidel/geo-location/tree/gh-pages) branch or better remove it completely?

**Comment by FluorescentHallucinogen** [comment]
@ebidel The https://ebidel.github.io/geo-location/ demo is 2 years old. Could you please remove it completely to not confuse users or at least update to the latest version?

**Comment by ebidel** [comment]
Killed the branch

**Comment by FluorescentHallucinogen** [comment]
@ebidel Thanks!
