### ISSUE TITLE
Current GPS accuracy

### ISSUE THREAD

**Issue by benquan** [ebidel/geo-location#33]
Is there a way to incorporate GPS accuracy estimate? I am pretty sure the data should be provided.

**Comment by ebidel** [comment]
Is that in the geolocation api?

**Comment by benquan** [comment]
Yeap. I added a pull request if you wish to incorporate it.

**Comment by FluorescentHallucinogen** [comment]
@ebidel Could this issue be closed?

**Comment by ebidel** [comment]
See https://github.com/ebidel/geo-location/pull/34
