### ISSUE TITLE
Your component is featured on one of the Vaadin blogs

### ISSUE THREAD

**Issue by binbalenci** [ebidel/geo-location#38]
Hey Eric,

I am Binh Bui, the Marketing Community Specialist of Vaadin. I tested your components and really liked it. I published the blog [Introducing geo-location, a web component which lets you easily locate, track or reverse geocode your current location](https://vaadin.com/blog/introducing-geo-location-a-web-component-which-lets-you-easily-locate-track-or-reverse-geocode-your-current-location).

Also, I would highly appreciate if there are some words down below the comment section from the original author.

Cheers!

**Comment by ebidel** [comment]
Very nice! Thanks for the write up :)
